#!/bin/bash

# Setup env parameters
MQTT_SERVER="tls://mqtt.openchirp.io:8883"
MQTT_USER="openchirp_pubsub"
MQTT_PASS="PASSWORD"
#REDIS_SERVER="localhost:6379"
#REDIS_PASS=""
REDIS_DB=1
LOG_LEVEL=5
SYSTEMD=false

export MQTT_SERVER MQTT_USER MQTT_PASS
export REDIS_SERVER REDIS_PASS REDIS_DB
export LOG_LEVEL
export SYSTEMD

go run main.go
